version: "3.8"

services:
  backend:
    build: ./api
    container_name: yucadiax-backend
    restart: unless-stopped
    ports:
      - "3000:3000"   # acceso directo opcional
    environment:
      - PORT=3000

  frontend:
    build: .
    container_name: yucadiax-frontend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "8080:80"     # aqu√≠ entra el usuario (http://tu-vm:8080)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
