version: "3.8"

services:
  pwa:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: integradora-pwa
    restart: unless-stopped
    ports:
      - "8080:80"        # Dentro del contenedor es 80 (Nginx), afuera 8080
